-- ============================================================
-- Onam Pass — Supabase PostgreSQL Schema
-- Run this in your Supabase project's SQL Editor.
-- ============================================================

-- ─── 1. Create the students table ────────────────────────────────────────────

drop table if exists public.students cascade;

create table public.students (
    -- Primary key (UUID generated by Postgres)
    id uuid primary key default gen_random_uuid(),

    -- Unique human-readable pass identifier, e.g. ONAM-8F42A91C
    pass_id text unique not null,

    -- Student details
    name        text not null,
    class_name  text not null,
    roll_number text,
    department  text,

    -- Status: 'pending' or 'approved' only
    status text not null default 'pending'
        check (status in ('pending', 'approved')),

    -- Timestamps
    created_at  timestamptz not null default now(),
    approved_at timestamptz,

    -- Staff user UUID who approved (references auth.users)
    approved_by uuid references auth.users(id)
);

-- Index for fast pass_id lookups (QR scan queries)
create index if not exists idx_students_pass_id on public.students(pass_id);

-- Index for status queries (statistics)
create index if not exists idx_students_status on public.students(status);

-- ─── 2. Enable Row Level Security ─────────────────────────────────────────────

alter table public.students enable row level security;

-- ─── 3. RLS Policies ──────────────────────────────────────────────────────────

-- Policy: Authenticated staff can SELECT any student record
create policy "Authenticated staff can read passes"
    on public.students
    for select
    to authenticated
    using (true);

-- Policy: Authenticated staff can INSERT new passes
--   Enforces that new passes always start as 'pending'
create policy "Authenticated staff can create pending passes"
    on public.students
    for insert
    to authenticated
    with check (
        status = 'pending'
        and approved_at is null
        and approved_by is null
    );

-- Policy: NO direct UPDATE is allowed from the client.
--   All approvals go through the approve_pass() RPC function
--   which runs with SECURITY DEFINER (bypasses RLS).
--   This prevents clients from freely setting status = 'approved'.

-- ─── 4. Atomic Approval RPC Function ─────────────────────────────────────────
--
-- This function runs inside a transaction.
-- It checks status == 'pending' before approving,
-- preventing race conditions when two scanners scan simultaneously.
--
-- Returns:
--   'approved'          → success, pass was pending and is now approved
--   'already_approved'  → pass was already approved by another scanner
--   'not_found'         → pass ID does not exist
--
create or replace function public.approve_pass(
    p_pass_id    text,
    p_approved_by uuid
)
returns text
language plpgsql
security definer  -- runs as the function owner, bypassing RLS
set search_path = public
as $$
declare
    v_status text;
begin
    -- Lock the row for update to prevent concurrent modifications
    select status
    into   v_status
    from   public.students
    where  pass_id = p_pass_id
    for update;           -- row-level lock

    -- Handle "not found"
    if not found then
        return 'not_found';
    end if;

    -- Handle already approved
    if v_status = 'approved' then
        return 'already_approved';
    end if;

    -- Atomically approve
    update public.students
    set
        status      = 'approved',
        approved_at = now(),
        approved_by = p_approved_by
    where pass_id = p_pass_id
      and status  = 'pending';   -- double-check (optimistic lock)

    return 'approved';
end;
$$;

-- Grant execute permission to authenticated users only
grant execute on function public.approve_pass(text, uuid) to authenticated;

-- ─── 5. (Optional) Realtime ───────────────────────────────────────────────────
-- Enable Realtime on the students table so the dashboard stats update live.
-- Run this in the Supabase Dashboard → Database → Replication tab,
-- or uncomment and run:

-- alter publication supabase_realtime add table public.students;

-- ─── 6. Test Data (optional, remove before production) ────────────────────────
-- INSERT INTO public.students (pass_id, name, class_name, roll_number, department, status)
-- VALUES
--   ('ONAM-TEST0001', 'Adhithyan S', 'S6 CSE', '24', 'Computer Science', 'pending'),
--   ('ONAM-TEST0002', 'Priya R', 'S4 ECE', '12', 'Electronics', 'pending');
